version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: error-analyzer-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ErrorPatternAnalyzer
    volumes:
      - mongodb_data:/data/db
    networks:
      - error-analyzer

  # Optional: MongoDB Express for GUI
  mongo-express:
    image: mongo-express:latest
    container_name: error-analyzer-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - error-analyzer

volumes:
  mongodb_data:

networks:
  error-analyzer:
    driver: bridge
