name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore ErrorPatternAnalyzer.sln
    
    - name: Build
      run: dotnet build ErrorPatternAnalyzer.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ErrorPatternAnalyzer.sln --configuration Release --no-build --verbosity normal
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/TestResults/**/*.trx'
